services:
  # Web services:
  - type: web
    name: student-management-system
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: True
      - key: RENDER
        value: True
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: student-management-db
          property: connectionString

databases:
  - name: student-management-db
    databaseName: sms_db
    user: sms_user